[workspace]
resolver = "2"
members = [
    "artefacts/thalassa",
    "artefacts/theseus-common",
    "artefacts/theseus-device",
    "artefacts/theseus-upload",
    "serialport-rs",
    "util/xor55",
]
