#INF_OKNS_ROOT=${HOME}/backstreet/cs240lx/okeanos
INF_OKNS_ROOT=.

INF_BUILD_DIR=$(INF_OKNS_ROOT)/build
INF_BASE_DIR=$(INF_OKNS_ROOT)/infra
INF_DOC_DIR=$(INF_OKNS_ROOT)/doc
INF_SRC_DIR=$(INF_OKNS_ROOT)/artefacts

INF_PI_INSTALL=$(INF_CFG_CS240LX_2024_PATH)/bin/$(INF_CFG_PI_INSTALL_BINARY)

INF_STITCH_FROM_MD=$(INF_BASE_DIR)/scripts/stitch-from-md.sh

_ARM=$(INF_CFG_ARM_NONE_EABI_PATH)/bin/arm-none-eabi
INF_ARM_NONE_EABI_GCC=$(_ARM)-gcc
INF_ARM_NONE_EABI_OBJDUMP=$(_ARM)-objdump
INF_ARM_NONE_EABI_OBJCOPY=$(_ARM)-objcopy
