[build]
target = "armv6zk-none-eabihf.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[profile]
dev.panic = "abort"
release.panic = "abort"
