[package]
name = "quartz"
version = "0.1.0"
edition = "2024"

[dependencies]
lock_api = { version = "0.4.12", default-features = false }
bcm2835-lpa = "0.4.0"
thiserror = { version = "1.0", package = "thiserror-core", default-features = false }